id = input ("what's your id?")
fn = input ("what's your first name?")
sn = input ("what's your surname?")
em = input ("what's your email?")
tn = input ("what's your telephone number?")
file = open("details.txt", "w")
file.write (id+"\n")
file.write (fn+"\n")
file.write (sn+"\n")
file.write (em+"\n")
file.write (tn+"\n")
file.close()
